export const ApprovalConstants = {
    featureCode: {
        ROLE: '100008',
        USER: '100007',
        CHANNEL :'100041',
        TAXTYPE:'100029',
        GROUP:'100010',
        COUNTRY:'100040',
        PERMISSION: '100009',
        EXCHNAGERATE: '100015',
        WALLET_OWNER: '100006',
        WALLET_OWNER_USER: '100016',
        WALLET_OWNER_ADDRESS: '100017',
        WALLET_OWNER_BANK: '100018',
        WALLET_OWNER_DOCUMENT: '100019',
        SERVICETEMPLATE :'100021',
        TEMPLATE : '100011',
        FEECOMMISION : "100024",
        FEETEMPLATE :"100023",
        TRANSACTIONLIMIT :"100022",
        LOADMONEY : "100028",
        WALLETMANAGEMENT:"100036",
        EMONEYCREATION:"100028",
        INCENTIVETEMPLATE :"100033",
        SERVICE : "100042",
        PRODUCT : "100043",
        OPERATOR : "100044",
        TaxType:"100029",
        TaxConfiguration :"100030",
        EMPLOYER:'100034',
        MERCHANT:'100037',
        SUBSCRIBER:'100035',
        WALLETTRANSFER:'100031',
        OWNERWALLET:"100046",
        OWNERTEMPLATE:"100047",
        TRANSACTIONREVERSAL:"100045"
       
       
    },
    featureName: {
        ROLE: 'Role',
        WALLET_OWNER: 'Wallet Owner',
        SYSTEM_USER: 'System User',
        PERMISSION: 'Permission',
        GROUPS: 'Groups',
        TEMPLATE: 'Template',
        CURRENCY: 'Currency',
        COUNTRY : 'Country',
        SERVICE_CATEGORY: 'serviceCategory',
        SERVICE_PROVIDER:'serviceProvider',
        // LOADMONEY:'LoadMoney',
        EMONEYCREATION:'E-Money Creation',
        TRANSACTIONREVERSAL:'Reversal'
        
    },
    status: {
        code: {
            CLAIMED: 'I',
            APPROVED: 'A',
            NEW: 'NE',
            REJECTED: 'R',
            CREATED: 'U',
            UPDATED: 'UP',
            ACTIVE: 'Y',
            INACTIVE: 'N',
            DISCLAIMED: 'U',
            ENROLLED: 'EN',
            SUSPENDED: 'S',
            BLOCKED: 'B',
            TERMINATED: 'T',
            IN_TRANSIT: 'IT'
        },
        text: {
            UPDATED: 'Updated',
            CREATED: 'Created',
            CLAIMED: 'Claimed',
            APPROVED: 'Approved',
            REJECTED: 'Rejected',
            DISCLAIMED: 'Disclaimed',
            ACTIVE: 'Active',
            INACTIVE: 'Inactive',
            NEW: 'New',
            ENROLLED: 'Enrolled',
            IN_PROGRESS: 'In Progress',
            SUSPENDED: 'Suspended',
            BLOCKED: 'Blocked',
            TERMINATED: 'Terminated',
            IN_TRANSIT : 'In Transit'
        }
    },
    state: {
        code: {
            CLAIMED: 'I',
            APPROVED: 'A',
            NEW: 'NE',
            REJECTED: 'R',
            CREATED: 'U',
            UPDATED: 'UP',
            DISCLAIMED: 'U',
            ENROLLED: 'EN',
            SUSPENDED: 'S',
            BLOCKED: 'B',
            TERMINATED: 'T',
            IN_TRANSIT: 'IT',
            IN_PROGRESS: 'I'
        },
        text: {
            UPDATED: 'Updated',
            CREATED: 'Created',
            CLAIMED: 'Claimed',
            APPROVED: 'Approved',
            REJECTED: 'Rejected',
            DISCLAIMED: 'Disclaimed',
            NEW: 'New',
            ENROLLED: 'Enrolled',
            IN_PROGRESS: 'In Progress',
            SUSPENDED: 'Suspended',
            BLOCKED: 'Blocked',
            TERMINATED: 'Terminated',
            IN_TRANSIT : 'In Transit'
        }
    }
};